# Generated by Django 4.0.4 on 2022-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.TextField(max_length=30)),
                ('cantidad_de_articulos', models.IntegerField()),
                ('articulo', models.TextField(max_length=30)),
                ('articulo2', models.TextField(max_length=30)),
                ('articulo3', models.TextField(max_length=30)),
                ('articulo4', models.TextField(max_length=30)),
                ('observaciones', models.TextField(max_length=1000)),
            ],
        ),
    ]
