# Generated by Django 4.0.4 on 2022-06-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField(max_length=200)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('stock', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
