# Generated by Django 4.0.4 on 2022-06-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregasApp', '0002_entregas_horario2_alter_entregas_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregas',
            name='horario2',
        ),
        migrations.AlterField(
            model_name='entregas',
            name='cantidad_de_productos_a_entregar',
            field=models.PositiveIntegerField(),
        ),
    ]
