# Generated by Django 4.0.4 on 2022-06-04 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EntregasApp', '0003_remove_entregas_horario2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregas',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
