# Generated by Django 4.0.4 on 2022-06-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregasApp', '0004_entregas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='entreCalles1',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='entregas',
            name='entreCalles2',
            field=models.TextField(max_length=10),
        ),
    ]
